#!/bin/bash -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cmd="uwsgi --plugin python --http-socket 0.0.0.0:8798 --wsgi-file tvflask.py --callable app"

pid_file="$DIR/pid"

log_file="$DIR/log"

get_pid() {
	cat "$pid_file"
}

is_running() {
	[ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
}

case "$1" in
	start)
		if is_running; then
			echo "Already started"
		else
			echo "Starting"
			cd "$DIR"
			$cmd >> "$log_file" 2>&1 &
			echo $! > "$pid_file"
		fi
		if ! is_running; then
			echo "Unable to start, see $log_file"
			exit 1
		fi
	;;
	stop)
		if is_running; then
			echo "Stopping"
			kill `get_pid`
			for i  in {1..10}
			do
				if ! is_running; then
					break
				fi
			done
			if is_running; then
				echo "Not stopped"
				exit 1
			else
				echo "Stopped"
				if [ -f "$pid_file" ]; then
					rm "$pid_file"
				fi
			fi
		else
			echo "Not running"
		fi
	;;
	restart)
		"$0" stop
		if is_running; then
			echo "Unable to stop, will not attempt to start"
			exit 1
		fi
		"$0" start
	;;
	*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
